CREATE TYPE "UserRole_new" AS ENUM (
  'SUPER_ADMIN',
  'HR_MANAGER',
  'PAYROLL_MANAGER',
  'EMPLOYEE'
);

ALTER TABLE "User"
ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User"
ALTER COLUMN "role" TYPE "UserRole_new"
USING (
  CASE "role"::text
    WHEN 'ADMIN' THEN 'SUPER_ADMIN'
    WHEN 'HR' THEN 'HR_MANAGER'
    WHEN 'FINANCE' THEN 'PAYROLL_MANAGER'
    WHEN 'MANAGER' THEN 'HR_MANAGER'
    WHEN 'USER' THEN 'EMPLOYEE'
    WHEN 'ANALYST' THEN 'EMPLOYEE'
    ELSE 'EMPLOYEE'
  END
)::"UserRole_new";

ALTER TYPE "UserRole" RENAME TO "UserRole_old";
ALTER TYPE "UserRole_new" RENAME TO "UserRole";
DROP TYPE "UserRole_old";

ALTER TABLE "User"
ALTER COLUMN "role" SET DEFAULT 'EMPLOYEE';
